name: Build and Push PostgreSQL Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Ensure that DOCKER_USERNAME and DOCKER_PASSWORD are set in your repository's secrets at
          # https://github.com/<owner>/<repo>/settings/secrets/actions

      - name: Build PostgreSQL Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: your-dockerhub-username/postgres-image:latest

      - name: Logout from Docker Hub
        run: docker logout